# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

# Python linting with pylint
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a5  # You can check the latest release of pylint
    hooks:
    -   id: pylint
        name: Pylint checks

# Python code formatter (black)
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        language_version: python3  # Specify Python version


# Sort Python imports with isort
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort
        name: Sort imports with isort


# Python security checks with bandit
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
    -   id: bandit
        name: Security checks
