{
 "title": "Credit Card Approval MLOps Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Prediction Drift Score",
   "type": "table",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT prediction_drift FROM dummy_metrics LIMIT 1 "
    }
   ]
  },
  {
   "title": "Number of Drifted Colums",
   "type": "table",
   "gridPos": { "h": 4, "w": 11, "x": 11, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT num_drifted_columns FROM dummy_metrics LIMIT 1 "
    }
   ]
  },
  {
   "title": "Missing Values Share",
   "type": "table",
   "gridPos": { "h": 4, "w": 11, "x": 5, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT share_missing_values FROM dummy_metrics LIMIT 1"
    }
   ]
  }
 ]
}