name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # Step 1: Build Docker image and push to Docker Hub
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/credit-card-approval-model:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/credit-card-approval-model:latest

  # Step 2: Pull Docker image locally and run it
  deploy-locally:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Docker image from Docker Hub
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/credit-card-approval-model:latest

      - name: Stop and remove any existing container
        run: |
          docker stop credit-card-app || true
          docker rm credit-card-app || true

      - name: Run Docker container locally
        run: |
          docker run -d -p 5000:5000 --name credit-card-app ${{ secrets.DOCKER_USERNAME }}/credit-card-approval-model:latest
