name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  # Step 1: Setup Python environment, install dependencies, and run tests
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.4' # Updated Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          pytest tests/test_train.py --maxfail=1 --disable-warnings

  # Step 2: Linting using pylint to ensure code follows standards
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.4'

      - name: Install linting dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Lint code with pylint
        run: |
          pylint **/*.py

  # Step 3: Validate Dockerfile syntax
  docker-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install hadolint
        run: sudo apt-get install -y hadolint

      - name: Lint Dockerfile
        run: hadolint Dockerfile

  # Step 4: Build Docker image to ensure no build issues
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t credit-card-approval-model .
