name: Monitor and Retrain Model

on:
  schedule:
    - cron: '0 0 1 */3 *' # Runs once every 3 months on the 1st day at midnight

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.4'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run monitoring script
        run: |
          python evidently_monitoring.py

      - name: Check performance and retrain if necessary
        run: |
          python retrain_model.py
